### ISSUE TITLE
BannerCreation

### ISSUE THREAD

**Issue by JoaoPedroCarvalho** [carvalho2707/LOLStats#2]
Functions that generate a custom banner:
* Ranked Trim/Border
 - [x] *getLastSeasonRank()*
 - [x] *setTrim(rank)* (recebe o rank e coloca na página a trim correta)
* Summoner Icon
 - [x] *setIcon(int icon)* (o icon é um atributo da classe summoner por isso não é preciso um *get*)
* Champion Banner
 - [x] *getLatestMostUsed()*  (vai buscar os ultimos 10 e vê o mais usado, se não houver vai buscar mais um e assim sucessivamente)
 - [x] *setChamp()*
* Summoner Name
 - [x] *setSummonerName()* (coloca o nome correcto no espaço do nome)
* Summoner Rank
 - [x] *getSummonerRank()* ([esta funcao da API](https://developer.riotgames.com/api/methods#!/985/3356) )
 - [x] *setSummonerRank()* (coloca a liga e a divisão no espaço do rank *"Silver II"*)

**Comment by carvalho2707** [comment]
setTrim e setIcon estão dependentes de tu podes as pics no git

**Comment by JoaoPedroCarvalho** [comment]
já tens lá todos os ficheiros. Já fizeste?

**Comment by carvalho2707** [comment]
acabei de manha as apis todas optimizadas e começei a por na tabela os metodos com ligação à bd..
Agora carregas no execute e o gajo vai à riot e mete na bd

**Comment by carvalho2707** [comment]
a pagina de supporte ja esta toda, mesmo boss
